### ISSUE TITLE
!streaklongest does not go back to 2017

### ISSUE THREAD

**Issue by mndowne** [adavila0703/dev-hub-bot#7]
I don't think that the !streaklongest feature in the bot goes all the way back to 2017. 

My longest streak was in 2017 but when I use !streaklongest it does not find that streak.

Thanks for any information or help     : - )

Best, 
Marty

**Comment by adavila0703** [comment]
GitHub only allows to go back one year, need to create pagination in GetContributionsByUsername to extract all the years.

![image](https://user-images.githubusercontent.com/36370758/144767411-600ada9f-58fe-4e4b-8f6b-16d29402a8ba.png)
